# Generated by Django 4.1.2 on 2022-10-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
