# Generated by Django 4.1.2 on 2022-10-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_video_lesson_delete_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.lesson'),
            preserve_default=False,
        ),
    ]
